INSERT INTO modalidades (nome, descricao, ativo) VALUES
('Surf', 'Desporto aquatico de prancha com ondas', TRUE),
('Skate', 'Desporto sobre rodas com prancha', TRUE),
('Skimboard', 'Desporto aquatico em aguas rasas', TRUE),
('Snowboard', 'Desporto de neve sobre prancha', TRUE),
('Sandboard', 'Desporto em dunas de areia', TRUE)
ON CONFLICT (nome) DO NOTHING;

INSERT INTO categorias (modalidade_id, nome, descricao) VALUES
((SELECT id FROM modalidades WHERE nome = 'Surf'), 'Shortboard', 'Manobras rapidas, aereas'),
((SELECT id FROM modalidades WHERE nome = 'Surf'), 'Fish', 'Mais largo, bom para ondas pequenas/medias'),
((SELECT id FROM modalidades WHERE nome = 'Surf'), 'Funboard / Mini-malibu', 'Intermedio, facil de apanhar ondas'),
((SELECT id FROM modalidades WHERE nome = 'Surf'), 'Longboard', 'Estilo classico, nose ride'),
((SELECT id FROM modalidades WHERE nome = 'Surf'), 'Gun', 'Ondas grandes'),
((SELECT id FROM modalidades WHERE nome = 'Surf'), 'Softboard', 'Espuma, iniciante'),
((SELECT id FROM modalidades WHERE nome = 'Surf'), 'Big Wave', 'Ondas gigantes, tow-in as vezes'),
((SELECT id FROM modalidades WHERE nome = 'Surf'), 'Tow-in Surf', 'Rebocado por mota de agua'),
((SELECT id FROM modalidades WHERE nome = 'Surf'), 'Bodyboard', 'Prancha curta, deitado'),
((SELECT id FROM modalidades WHERE nome = 'Surf'), 'Bodysurf', 'Sem prancha'),
((SELECT id FROM modalidades WHERE nome = 'Surf'), 'Stand Up Paddle (SUP Surf)', 'Em pe com pagaia'),
((SELECT id FROM modalidades WHERE nome = 'Skate'), 'Street', 'Escadas, corrimoes, gaps'),
((SELECT id FROM modalidades WHERE nome = 'Skate'), 'Park', 'Skateparks, bowls pequenos, transicoes'),
((SELECT id FROM modalidades WHERE nome = 'Skate'), 'Vert', 'Half-pipe alto'),
((SELECT id FROM modalidades WHERE nome = 'Skate'), 'Bowl / Pool', 'Bacias/piscinas, transicoes fundas'),
((SELECT id FROM modalidades WHERE nome = 'Skate'), 'Freestyle', 'Manobras tecnicas/planas, old school vibe'),
((SELECT id FROM modalidades WHERE nome = 'Skate'), 'Downhill', 'Alta velocidade a descer'),
((SELECT id FROM modalidades WHERE nome = 'Skate'), 'Cruising', 'Passeio'),
((SELECT id FROM modalidades WHERE nome = 'Skate'), 'Longboard - Dancing', 'Passos/coreografias na prancha'),
((SELECT id FROM modalidades WHERE nome = 'Skate'), 'Longboard - Freeride', 'Slides controlados'),
((SELECT id FROM modalidades WHERE nome = 'Skate'), 'Slalom', 'Cones, agilidade'),
((SELECT id FROM modalidades WHERE nome = 'Skimboard'), 'Flatland', 'Em agua rasa, manobras no plano'),
((SELECT id FROM modalidades WHERE nome = 'Skimboard'), 'Wave Skimming', 'Apanhar ondas, mais parecido com surf'),
((SELECT id FROM modalidades WHERE nome = 'Skimboard'), 'Freestyle', 'Shuvs, spins, geralmente flat'),
((SELECT id FROM modalidades WHERE nome = 'Skimboard'), 'Technical / Tricks', 'Foco em manobras'),
((SELECT id FROM modalidades WHERE nome = 'Skimboard'), 'Cruising / Recreativo', 'Uso casual em praia rasa'),
((SELECT id FROM modalidades WHERE nome = 'Snowboard'), 'Freeride', 'Fora de pista, natural'),
((SELECT id FROM modalidades WHERE nome = 'Snowboard'), 'Freestyle', 'Manobras, park'),
((SELECT id FROM modalidades WHERE nome = 'Snowboard'), 'Park', 'Rails, boxes, kickers'),
((SELECT id FROM modalidades WHERE nome = 'Snowboard'), 'Jibbing', 'Slides em rails/caixas'),
((SELECT id FROM modalidades WHERE nome = 'Snowboard'), 'Halfpipe', 'Pipe grande'),
((SELECT id FROM modalidades WHERE nome = 'Snowboard'), 'Slopestyle', 'Linha com obstaculos e saltos'),
((SELECT id FROM modalidades WHERE nome = 'Snowboard'), 'Big Air', 'Um salto enorme'),
((SELECT id FROM modalidades WHERE nome = 'Snowboard'), 'Boardercross / Snowboard Cross', 'Corrida em pista com obstaculos'),
((SELECT id FROM modalidades WHERE nome = 'Snowboard'), 'Alpine / Carving', 'Curvas agressivas, prancha mais rigida'),
((SELECT id FROM modalidades WHERE nome = 'Snowboard'), 'Splitboard', 'Subida em modo ski e descida snowboard'),
((SELECT id FROM modalidades WHERE nome = 'Snowboard'), 'Backcountry', 'Montanha, neve natural'),
((SELECT id FROM modalidades WHERE nome = 'Sandboard'), 'Freeride', 'Descer dunas, estilo livre'),
((SELECT id FROM modalidades WHERE nome = 'Sandboard'), 'Downhill / Speed', 'Velocidade maxima'),
((SELECT id FROM modalidades WHERE nome = 'Sandboard'), 'Freestyle', 'Saltos e manobras'),
((SELECT id FROM modalidades WHERE nome = 'Sandboard'), 'Dune Jumping', 'Foco em airs/saltos'),
((SELECT id FROM modalidades WHERE nome = 'Sandboard'), 'Carving', 'Curvas desenhadas, controlo'),
((SELECT id FROM modalidades WHERE nome = 'Sandboard'), 'Boardercross', 'Pista com obstaculos/curvas, corrida'),
((SELECT id FROM modalidades WHERE nome = 'Sandboard'), 'Sled / Sit-down', 'Variacoes sentado - mais recreativo')
ON CONFLICT (modalidade_id, nome) DO NOTHING;
